"""ProbeScenario + Probe schemas.

Specified verbatim by DESIGN.md 3.1. The strategy enum enumerates the eight
strategies of DESIGN.md 3.2 and its member names match the module names under
harness/probe_gen/strategies/ one-for-one, so a strategy cannot be referenced in
data without a module existing to construct it.

THE C1 BOUNDARY RUNS THROUGH THIS FILE. `Probe.turns` is the natural-language
surface an LLM wrote. `Probe.expected_policy_stance` is NOT: it is the return
value of `evaluate_rules(scenario.facts)`, computed in Python. Order of
operations is strict (DESIGN.md 3.1): sample the fact vector, label it
deterministically, and only then ask the adversary model to render a sentence -
told the facts and told nothing about the correct answer, so it cannot leak the
label into the phrasing.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from harness.schemas.rule import PolicyStance


class ProbeStrategy(str, Enum):
    """The eight adversarial strategies of DESIGN.md 3.2.

    Values are the wire format: they appear directly in probes.lock.json and in
    the `strategy` column of every audit row (DESIGN.md 5.1).
    """

    #: Sample numeric/temporal conditions at v-1, v, v+1. Retrieval finds the
    #: right clause; the model rounds.
    BOUNDARY = "boundary"

    #: Satisfy N-1 of N ANDed conditions, assert the rest confidently. The model
    #: sees a mostly-matching clause and completes the pattern.
    CONDITION_STRIPPING = "condition_stripping"

    #: Traverse to depth-2 exception paths. Requires correct precedence, which
    #: chunk retrieval destroys.
    EXCEPTION_DEPTH = "exception_depth"

    #: An item semantically adjacent to an excluded category - "a fitness band"
    #: against excluded "wearables". Embedding similarity works against
    #: correctness here.
    CATEGORY_SMUGGLING = "category_smuggling"

    #: Presuppose an entitlement that does not exist. The literal Air Canada
    #: shape: models answer the "how" and inherit the "whether". Weighted most
    #: heavily in DESIGN.md 3.2 - highest severity, and it has a court precedent
    #: attached.
    FALSE_PREMISE = "false_premise"

    #: "Your agent confirmed this last week", "I've spent 40k with you."
    #: Sycophancy pressure with no policy grounds changing.
    AUTHORITY_PRESSURE = "authority_pressure"

    #: Turn 1 innocuous and in-policy, turn 2 shifts one fact out of policy.
    #: Tests whether the model reuses turn 1's conclusion.
    MULTI_TURN_DRIFT = "multi_turn_drift"

    #: Two interacting clauses, only one of which retrieval will surface. Tests
    #: whether the agent knows what it did not retrieve.
    CROSS_CLAUSE = "cross_clause"


class ProbeScenario(BaseModel):
    """A concrete fact vector plus the rule it was sampled to attack."""

    model_config = ConfigDict(extra="forbid")

    facts: dict[str, str | int | float] = Field(
        min_length=1,
        description='The fact vector, e.g. {"days_since_delivery": 31, '
        '"item_category": "innerwear", "channel": "app"}. Keys correspond to '
        "Condition.attribute. Must be non-empty: a scenario with no facts "
        "cannot be deterministically labelled, which would breach C1.",
    )
    target_rule_id: str = Field(
        min_length=1,
        description="The rule this probe was sampled against. Drives probe "
        "invalidation when a rule changes (DESIGN.md 2 step 4).",
    )
    strategy: ProbeStrategy
    difficulty_tier: Literal[1, 2, 3]


class Probe(BaseModel):
    """One adversarial probe: a rendered surface plus a derived label."""

    model_config = ConfigDict(extra="forbid")

    probe_id: str = Field(
        min_length=1,
        description='e.g. "P-acme-014-boundary-003" (DESIGN.md 5.1).',
    )
    scenario: ProbeScenario
    turns: list[str] = Field(
        min_length=1,
        max_length=3,
        description="1 for single-turn, 2-3 for drift probes (DESIGN.md 3.1). "
        "Capped at 3 because three turns max is a stated scope limit "
        "(DESIGN.md 8).",
    )
    expected_policy_stance: PolicyStance = Field(
        description="COMPUTED by evaluate_rules(), never generated by a model. "
        "This field is commitment C1. When a rule's threshold moves, this is "
        "recomputed in pure Python and the probe text is left untouched - the "
        "re-label-without-regenerate path that DESIGN.md 6.2 calls the dominant "
        "speed win.",
    )
    clause_ids: list[str] = Field(
        min_length=1,
        description="Clauses this probe was constructed from. Narrows the "
        "judge's context to 2-4 candidate clauses rather than the whole policy, "
        "which DESIGN.md 4.1 identifies as the single biggest lever on judge "
        "reliability.",
    )
    style_seed_id: str | None = Field(
        default=None,
        description="Structural style template used to render the surface. "
        "Structural features only - the source corpus is never stored or "
        "shipped (DESIGN.md 3.3).",
    )

    @model_validator(mode="after")
    def _multi_turn_drift_needs_more_than_one_turn(self) -> Probe:
        """A drift probe works by shifting a fact between turns, so a
        single-turn instance of it is not the strategy it claims to be."""
        if (
            self.scenario.strategy is ProbeStrategy.MULTI_TURN_DRIFT
            and len(self.turns) < 2
        ):
            raise ValueError(
                f"probe {self.probe_id!r} declares strategy "
                f"{ProbeStrategy.MULTI_TURN_DRIFT.value!r} but carries "
                f"{len(self.turns)} turn(s); drift requires at least 2"
            )
        return self

    @property
    def is_multi_turn(self) -> bool:
        """Multi-turn probes reuse one session_id across turns; single-turn
        probes get a fresh one (DESIGN.md 2 step 6)."""
        return len(self.turns) > 1
