"""Generate a candidate probe set with the LLM adversary, oracle-check it.

This is a MEASUREMENT exercise, mirroring `scripts/extract_and_compare.py`. It
reads the hand-authored `rules.lock.json` (never regenerates rules), samples
fact vectors per strategy, renders surfaces with the adversary LLM (temp 0.9),
self-critiques each, oracle-checks the result against `evaluate_rules()`, and
writes the survivors to `probes/probes.generated.json` — never to
`probes.lock.json`.

Usage:
    python scripts/generate_probes.py [--limit-per-rule N] [--model M]

Requires an adversary model (local by default; see CLAUSEGUARD_ADVERSARY_MODEL).
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from harness.execution.lockfiles import DEFAULT_RULES_LOCK, PROBES_LOCK_SCHEMA, load_rules
from harness.ingest import ingest
from harness.probe_gen.adversary import (
    LitellmAdversaryClient,
    resolve_adversary_model,
    resolve_adversary_temp,
)
from harness.probe_gen.driver import STRATEGY_ORDER, generate_probes

POLICY_SOURCE = "policies/acme-refunds.md"
OUT_PATH = Path("probes/probes.generated.json")


def _write_generated(path: Path, *, probes, policy, model: str, stats: dict, digest: str) -> Path:
    payload = {
        "schema": PROBES_LOCK_SCHEMA,
        "policy_doc": policy.doc_slug,
        "policy_version": policy.policy_version,
        "rules_digest": digest,
        "authored_by": f"generated by scripts/generate_probes.py (adversary {model}); oracle-checked",
        "probes": [p.model_dump(mode="json") for p in probes],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate and oracle-check candidate probes.")
    parser.add_argument("--limit-per-rule", type=int, default=1,
                        help="Max probes per (rule, strategy) (default 1)")
    parser.add_argument("--rules", type=int, default=None,
                        help="Only process the first N root rules (for a quick checkpoint run)")
    parser.add_argument("--model", default=None, help="Override adversary model")
    parser.add_argument("--timeout", type=int, default=None, help="Per-call timeout (s)")
    args = parser.parse_args(argv)

    policy = ingest(POLICY_SOURCE, corpus_role="worked_example")
    rules = load_rules(DEFAULT_RULES_LOCK)
    print(f"policy      : {policy.doc_slug}  {policy.policy_version}")
    print(f"rules       : {len(rules.rules)} root rule(s)")

    rule_subset = rules.rules if args.rules is None else rules.rules[:args.rules]

    model = args.model or resolve_adversary_model()
    client = LitellmAdversaryClient(model=model, timeout_s=args.timeout or 240)
    print(f"adversary   : {client.model}  (temperature {resolve_adversary_temp()})")

    result = generate_probes(
        rule_subset, policy, client=client, limit_per_rule=args.limit_per_rule
    )

    # Compute the correct rules_digest so clauseguard run accepts this file.
    from harness.execution.lockfiles import rules_digest
    digest = rules_digest(rules.rules)

    path = _write_generated(
        OUT_PATH, probes=result["generated"], policy=policy,
        model=client.model, stats=result["stats"], digest=digest,
    )
    print(f"written     : {path}  ({len(result['generated'])} probes)")
    print(f"  probes.lock.json untouched (hand-authored source of truth)")

    # ---- Report ----
    print("\n-- ORACLE / VALIDITY REPORT --")
    s = result["stats"]
    total = sum(s.get(k, 0) for k in ("oracle_passed", "oracle_failed"))
    print(f"  sampled        : {s.get('sampled', 0)}")
    print(f"  unlabellable   : {s.get('unlabellable', 0)}")
    print(f"  render_error   : {s.get('render_error', 0)}")
    print(f"  oracle passed  : {s.get('oracle_passed', 0)}")
    print(f"  oracle failed  : {s.get('oracle_failed', 0)}")
    if total:
        print(f"  oracle pass rate: {s.get('oracle_passed', 0)/total:.1%}")

    print("\n-- STRATEGY DISTRIBUTION (attempted / passed) --")
    for strat in STRATEGY_ORDER:
        attempted = result["attempted"].get(strat.value, 0)
        passed = result["passed"].get(strat.value, 0)
        print(f"  {strat.value:<22} attempted {attempted:>3}   passed {passed:>3}")

    # Compare against DESIGN.md 3.2's allocation and 8's yield expectation.
    print("\n-- VS DESIGN.md --")
    print("  DESIGN.md 3.2 allocation: 20% false_premise, 20% boundary, 15% stripping, 10% exception, 10% smuggling, 10% authority, 10% multi-turn, 5% cross-clause")
    print("  DESIGN.md 8 expectation: false_premise / multi-turn would dominate over-promise YIELD.")
    print("  Hand-written corpus finding (docs/results.md): condition_stripping dominates instead.")
    print("  This generated set is a first pass; yield-by-strategy needs a judged run to compare.")
    print("  Per-strategy attempted/passed counts above — the oracle pass rate is the ratio.")

    return 0


if __name__ == "__main__":
    sys.exit(main())